/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesNewRouteImport } from './routes/updates.new'
import { Route as UpdatesIdRouteImport } from './routes/updates.$id'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesNewRoute = UpdatesNewRouteImport.update({
  id: '/updates/new',
  path: '/updates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIdRoute = UpdatesIdRouteImport.update({
  id: '/updates/$id',
  path: '/updates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manager': typeof ManagerRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/updates/new': typeof UpdatesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manager': typeof ManagerRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/updates/new': typeof UpdatesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manager': typeof ManagerRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/updates/new': typeof UpdatesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/manager' | '/updates/$id' | '/updates/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/manager' | '/updates/$id' | '/updates/new'
  id: '__root__' | '/' | '/auth' | '/manager' | '/updates/$id' | '/updates/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ManagerRoute: typeof ManagerRoute
  UpdatesIdRoute: typeof UpdatesIdRoute
  UpdatesNewRoute: typeof UpdatesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/new': {
      id: '/updates/new'
      path: '/updates/new'
      fullPath: '/updates/new'
      preLoaderRoute: typeof UpdatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$id': {
      id: '/updates/$id'
      path: '/updates/$id'
      fullPath: '/updates/$id'
      preLoaderRoute: typeof UpdatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ManagerRoute: ManagerRoute,
  UpdatesIdRoute: UpdatesIdRoute,
  UpdatesNewRoute: UpdatesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
